version: "3.8"
services:
    rabbitmq-api:
      networks:
        - default
      container_name: rabbitmq-api
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8080

        - POSTGRES_URL=jdbc:postgresql://db:5432/rabbitmq-db
        - POSTGRES_DB=rabbitmq-db
        - POSTGRES_USER=admin
        - POSTGRES_PASS=root

        - RABBITMQ_HOST=message_broker
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASS=guest
      ports:
        - 8080:8080
    db:
      image: postgres:16.1-alpine3.19
      container_name: rabbitmq-db
      networks:
        - default
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
        POSTGRES_DB: rabbitmq-db
      ports:
        - 5432:5432
    message_broker:
      image: rabbitmq:3.13.3-management
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge